Updating
marcelogaray/auto-GA-v04 pull request #13
Opened 2018-06-18 22:25 UTC by ivanMise

2018-06-18 22:26 UTC, ivanMise commented
RF07-TC-002 CREATE EQUIPMENT

![image](https://user-images.githubusercontent.com/32719964/41565513-192713f2-7325-11e8-9b08-f7dd0947f61d.png)


![image](https://user-images.githubusercontent.com/32719964/41565517-2039d27e-7325-11e8-8fa9-bca56b0fb51d.png)

2018-06-18 23:36 UTC, ivanMise commented
![image](https://user-images.githubusercontent.com/32719964/41567573-ea995bc6-732e-11e8-8b81-2ad88a9ea3ee.png)

2018-06-20 13:04 UTC, marcelogaray requested changes
review observations

2018-06-20 13:04 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/RegisterEquipment/RegisterEquipment.java
> +        String equiName = PropertyAccessor.getInstance().getEquiName();
slipt your steps in this method

2018-06-20 13:04 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        this.registerEquipment = new RegisterEquipment();
in the "step definition" you dont need to create the Page Object.
for this pull request just you need to send "registerEquipment()" method of the RegisterEquipment class.

2018-06-20 13:04 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        login.setCredentials();
once you have the credentials you need some page object Dashboard/Header/MenuMain/etc etc etc

2018-06-20 20:50 UTC, closed without merging