Rf04 tc 126 list resources
marcelogaray/auto-GA-v04 pull request #29
Opened 2018-06-21 23:39 UTC by marbusjim

TC list of resources

2018-06-21 23:43 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41750705-5c946a32-758b-11e8-93f9-f174776b95d6.png)

2018-06-21 23:44 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41750728-6f8df946-758b-11e8-8584-6765f050c87d.png)

2018-06-21 23:54 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41750988-f1afd04c-758c-11e8-997a-e22073878430.png)

2018-06-22 00:58 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41752505-d7157292-7595-11e8-931f-bc57fda65f44.png)

2018-06-22 01:12 UTC, marcelogaray requested changes
review observations

2018-06-22 01:12 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/Menu.java
> +    public SubMenuProgramSSO clickMenuProgramSSO(){
clickProgramSSOMenu

2018-06-22 01:12 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Home/Home.java
>      public Menu getHomeMenu() {
improve this method please.

2018-06-22 01:12 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/CucumberRunner.java
> +        ,tags = "@resource"
remove this value

2018-06-22 01:12 UTC, marcelogaray commented on src/test/resources/features/Resource/Resource.feature
> +     And seleccionar sub menu 'Recursos'
seleccionar  'Recurso' submenu en 'Header' page

2018-06-22 01:12 UTC, marcelogaray commented on src/test/resources/features/Resource/Resource.feature
> +     Given Menu principal estee cargado
remove it

2018-06-22 01:37 UTC, marcelogaray requested changes
review observations

2018-06-22 01:37 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +    public Boolean visibilityCostHeader(){
publiv void visibitlyCost

2018-06-22 01:37 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        return resource.visibilityCostHeader();
Assert.assertTrue(resource.visibilityCostHeader(), "mensaje error")

2018-06-22 03:36 UTC, marcelogaray requested changes
review observations

2018-06-22 03:36 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/Menu.java
> +
it should be careful with merge, in this point you need to add a close braces.

2018-06-22 03:36 UTC, marcelogaray commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +
it should be careful with merge, in this point you need to add a close braces.

2018-06-22 04:27 UTC, marbusjim reviewed
Please add more detail about your observations

2018-06-22 04:27 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Home/Home.java
>      public Menu getHomeMenu() {
What do you think we will need add or modified, this code it was approve of you in previous pull request

2018-06-22 17:46 UTC, marcelogaray commented
we are going to close it, please let me know when you will fix your conflicts(merge with development)

2018-06-22 23:26 UTC, marbusjim commented
Reopen with improvements

2018-06-25 03:49 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41829510-2da74372-7809-11e8-8e97-5c428db94587.png)

2018-06-25 03:50 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41829526-4d253876-7809-11e8-998a-2f5b46125946.png)

2018-06-25 04:26 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41830358-69943e3a-780e-11e8-973b-5c3249fa4906.png)

2018-06-25 17:54 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41866791-3098e5ce-787f-11e8-8b53-006175b459da.png)

2018-06-26 01:07 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41883257-ad877b22-78bb-11e8-8291-52433c5c5db2.png)

2018-06-26 01:51 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41883288-d2643c78-78bb-11e8-9281-648c1c174d9a.png)

2018-06-26 03:57 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41888457-8a496680-78d3-11e8-92c9-618198f03f03.png)

2018-06-26 03:58 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41888476-a6352c6c-78d3-11e8-8695-8dae73950e53.png)

2018-06-26 04:51 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41889923-17f8df7c-78db-11e8-8855-b3814647defd.png)

2018-06-26 04:54 UTC, marbusjim commented
![image](https://user-images.githubusercontent.com/19719086/41889971-5211d48e-78db-11e8-8022-a48f556b8887.png)

2018-06-27 23:30 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement costHeader;
invertir el nombre Ej.: headerCost

2018-06-27 23:30 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement detailHeader;
invertir el nombre Ej.: headerDetail

2018-06-27 23:31 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement actionHeader;
invertir el nombre Ej.: headerAction

2018-06-27 23:31 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement addResourceButton;
invertir el nombre Ej.: buttonAddResource

2018-06-27 23:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement resourceList;
invertir el nombre Ej.: listResource

2018-06-27 23:34 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public boolean visibilityCostHeader() {
change name Ej.: validateHeaderCostIsVisible

2018-06-27 23:34 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public boolean visibilityDetailHeader() {
change name Ej.: validateHeaderDetailIsVisible

2018-06-27 23:35 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public boolean visibilityActionHeader() {
change name Ej.: validateHeaderActionIsVisible

2018-06-27 23:35 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public ResourceForm clickAddResourceButton(){
change name Ej.: clickButtonAddResource

2018-06-27 23:35 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public boolean isVisibleListResource(){
change name Ej.: validateListResourceIsVisible

2018-06-27 23:36 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement costInputField;
change name Ej.: inputFieldCost

2018-06-27 23:37 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement detailInputField;
change name Ej.: inputFieldDetail

2018-06-27 23:37 UTC, cmtp commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +import cucumber.api.java.en_scouse.An;
Please delete this unnecesary import

2018-06-27 23:38 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement saveBtn;
change name Ej.: buttonSave

2018-06-27 23:38 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement backButton;
change name Ej.: buttonBack

2018-06-27 23:38 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement cancelButton;
change name Ej.: buttonCancel

2018-06-27 23:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    public boolean isTitleValid(String title){
change name Ej.: validateTitleIsVisible

2018-06-27 23:43 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    public boolean isVisibleCostInputField(){
change name Ej.: validateInputFieldCostIsVisible

2018-06-27 23:43 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    public boolean isVisibleDetailInputField(){
change name Ej.: validateInputFieldDetailIsVisible

2018-06-27 23:43 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    public Resource clickCancelButton(){
change name Ej.: clickButtonCancel

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement costHeader;
done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement detailHeader;
done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement actionHeader;
done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement addResourceButton;
done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    private WebElement resourceList;
done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public boolean visibilityCostHeader() {
Done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public boolean visibilityDetailHeader() {
done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public boolean visibilityActionHeader() {
done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public ResourceForm clickAddResourceButton(){
done

2018-06-27 23:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/Resource.java
> +    public boolean isVisibleListResource(){
done

2018-06-27 23:45 UTC, jdpapiero commented on src/test/resources/features/Resource/AddResource.feature
> +  And menu 'Programa SSO' este seleccionado de la pagina 'Home'
suggestion: seleccionar la opcion 'Programa SSO' del menu principal

2018-06-27 23:46 UTC, jdpapiero commented on src/test/resources/features/Resource/AddResource.feature
> +  And seleccionar sub menu 'Recursos'
suggestion: seleccionar la opcion 'Recursos' en el sub menu de 'Programa SSO'

2018-06-27 23:48 UTC, jdpapiero commented on src/test/resources/features/Resource/AddResource.feature
> +  Then validar que la lista de la pagina 'Recursos' este visible
add a step click Save form

2018-06-27 23:49 UTC, jdpapiero commented on src/test/resources/features/Resource/Resource.feature
> +     And menu 'Programa SSO' este seleccionado de la pagina 'Home'
suggestion: seleccionar la opcion 'Programa SSO' del menu principal

2018-06-27 23:49 UTC, jdpapiero commented on src/test/resources/features/Resource/Resource.feature
> +     And seleccionar sub menu 'Recursos'
suggestion: seleccionar la opcion 'Recursos' en el sub menu de 'Programa SSO'

2018-06-27 23:51 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement costInputField;
done

2018-06-27 23:52 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement detailInputField;
done

2018-06-27 23:52 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement saveBtn;
done

2018-06-27 23:53 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement backButton;
done

2018-06-27 23:53 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    private WebElement cancelButton;
done

2018-06-27 23:53 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    public boolean isTitleValid(String title){
done

2018-06-27 23:55 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    public boolean isVisibleCostInputField(){
done

2018-06-27 23:55 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    public boolean isVisibleDetailInputField(){
done

2018-06-27 23:55 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/ProgramSSO/ResourceForm.java
> +    public Resource clickCancelButton(){
done

2018-06-27 23:58 UTC, jdpapiero requested changes
review comments

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValButtonBackAddResource.feature
> +      And seleccionar sub menu 'Recursos'
suggestion: seleccionar la opcion 'Recursos' en el sub menu de 'Programa SSO'

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValButtonBackAddResource.feature
> +      And menu 'Programa SSO' este seleccionado de la pagina 'Home'
suggestion: seleccionar la opcion 'Programa SSO' del menu principal

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValButtonCancelAddResource.feature
> +      And menu 'Programa SSO' este seleccionado de la pagina 'Home'
suggestion: seleccionar la opcion 'Programa SSO' del menu principal

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValInputFieldResourceForm.feature
> +      And menu 'Programa SSO' este seleccionado de la pagina 'Home'
suggestion: seleccionar la opcion 'Programa SSO' del menu principal

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValTitleResourceForm.feature
> +      And menu 'Programa SSO' este seleccionado de la pagina 'Home'
suggestion: seleccionar la opcion 'Programa SSO' del menu principal

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValButtonCancelAddResource.feature
> +      And seleccionar sub menu 'Recursos'
suggestion: seleccionar la opcion 'Recursos' en el sub menu de 'Programa SSO'

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValInputFieldResourceForm.feature
> +      And seleccionar sub menu 'Recursos'
suggestion: seleccionar la opcion 'Recursos' en el sub menu de 'Programa SSO'

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValTitleResourceForm.feature
> +      And seleccionar sub menu 'Recursos'
suggestion: seleccionar la opcion 'Recursos' en el sub menu de 'Programa SSO'

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValTitleResourceForm.feature
> +    Scenario: RF04-TC-127 - Verificar la creacion de nuevos de Recursos
the scenario would be according Feature

2018-06-27 23:58 UTC, jdpapiero commented on src/test/resources/features/Resource/ValTitleResourceForm.feature
> +      Then validar si el titulo 'Crear Recurso' de la pagina de 'Agregar Recursos'
please clarify the step Then

2018-06-27 23:58 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +import cucumber.api.java.en_scouse.An;
done

2018-06-28 00:01 UTC, marbusjim commented on src/test/resources/features/Resource/AddResource.feature
> +  And menu 'Programa SSO' este seleccionado de la pagina 'Home'
Done

2018-06-28 00:17 UTC, marbusjim commented on src/test/resources/features/Resource/AddResource.feature
> +  And seleccionar sub menu 'Recursos'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/AddResource.feature
> +  Then validar que la lista de la pagina 'Recursos' este visible
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/Resource.feature
> +     And menu 'Programa SSO' este seleccionado de la pagina 'Home'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/Resource.feature
> +     And seleccionar sub menu 'Recursos'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValButtonBackAddResource.feature
> +      And menu 'Programa SSO' este seleccionado de la pagina 'Home'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValButtonBackAddResource.feature
> +      And seleccionar sub menu 'Recursos'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValButtonCancelAddResource.feature
> +      And menu 'Programa SSO' este seleccionado de la pagina 'Home'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValButtonCancelAddResource.feature
> +      And seleccionar sub menu 'Recursos'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValInputFieldResourceForm.feature
> +      And menu 'Programa SSO' este seleccionado de la pagina 'Home'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValInputFieldResourceForm.feature
> +      And seleccionar sub menu 'Recursos'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValTitleResourceForm.feature
> +    Scenario: RF04-TC-127 - Verificar la creacion de nuevos de Recursos
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValTitleResourceForm.feature
> +      And menu 'Programa SSO' este seleccionado de la pagina 'Home'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValTitleResourceForm.feature
> +      And seleccionar sub menu 'Recursos'
done

2018-06-28 01:57 UTC, marbusjim commented on src/test/resources/features/Resource/ValTitleResourceForm.feature
> +      Then validar si el titulo 'Crear Recurso' de la pagina de 'Agregar Recursos'
done

2018-06-28 02:26 UTC, danielrpg commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(resource.validateHeaderCostIsVisible(), "No se encuentra la columna 'Costo' en la pagina 'Recursos'");
This message need to be in ErrorMessage like constant for example:
ErrorMessage.ERROR_MESSAGE_COST_ELEMENT_VISIBLE

2018-06-28 02:26 UTC, danielrpg commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(resource.validateHeaderDetailIsVisible(), "No se encuentra la columna 'Detalle' en la pagina 'Recursos'");
This message need to be in ErrorMessage like constant for example:
ErrorMessage.ERROR_MESSAGE_DETAIL_ELEMENT_VISIBLE

2018-06-28 02:26 UTC, danielrpg commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(resource.validateHeaderActionIsVisible(), "No se encuentra la columna 'Accion' en la pagina 'Recursos'");
This message need to be in ErrorMessage like constant for example:
ErrorMessage.ERROR_MESSAGE_COLUMN_ELEMENT_VISIBLE

2018-06-28 02:35 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(resource.validateHeaderCostIsVisible(), "No se encuentra la columna 'Costo' en la pagina 'Recursos'");
done

2018-06-28 02:35 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(resource.validateHeaderDetailIsVisible(), "No se encuentra la columna 'Detalle' en la pagina 'Recursos'");
done

2018-06-28 02:35 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(resource.validateHeaderActionIsVisible(), "No se encuentra la columna 'Accion' en la pagina 'Recursos'");
done

2018-06-28 02:42 UTC, ctola91 approved these changes

2018-06-28 02:44 UTC, jdpapiero requested changes
review comment

2018-06-28 02:44 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/Menu.java
> +    public SubMenuProgramSSO clickProgramSSOMenu() {
please change name Ej.: clickMenuProgramSSO

2018-06-28 02:56 UTC, jdpapiero approved these changes

2018-06-28 02:59 UTC, danielrpg approved these changes
Aproved Changes

2018-06-28 02:59 UTC, merged