RF01 TC 019 Verificar Búsqueda de Personal
marcelogaray/auto-GA-v04 pull request #35
Opened 2018-06-22 21:45 UTC by franzelunico

![image](https://user-images.githubusercontent.com/4955089/41800520-edb49a56-7643-11e8-8466-068bee37e205.png)
![image](https://user-images.githubusercontent.com/4955089/41800547-0086e03a-7644-11e8-92c6-40a06d807fae.png)

2018-06-28 02:29 UTC, jdpapiero requested changes
review comments

2018-06-28 02:29 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
>      private WebElement usuarioSubMenu;
Change name WebElement. Ej.: subMenuUsuario

2018-06-28 02:29 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    private WebElement personalSubMenu;
Change name WebElement. Ej.: subMenuPersonal

2018-06-28 02:29 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personal/FindPersonal.java
> +    private WebElement itBuscarPersonal;
Change name WebElement. Ej.: inputFindPerson

2018-06-28 02:29 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personal/FindPersonal.java
> +    public boolean isFindPersonalVisible(){
change name method.: Ej.: validateInputFindPersonIsVisible()

2018-06-28 02:29 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personal/FindPersonal.java
> +    public void buscarPersonal(String personal){
try to use everithing in english. Ej.: setTextFindPerson(String person)

2018-06-28 02:29 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personal/FindPersonal.java
> +    public int personalEncontrado(int x){
try to use everything in english Ej.: validatePersonFound()

2018-06-28 02:29 UTC, jdpapiero commented on src/test/resources/features/Personal/Personal.feature
> +    And Seleccionar submenu 'Personal' en menu 'Personal'
the first letter in step description should be in lowercase

2018-06-28 02:29 UTC, jdpapiero commented on src/test/resources/features/Personal/Personal.feature
> +    When Ingresar <correo> para 'Buscar Personal' en la tabla
the first letter in step description should be in lowercase
is necessary describe better this step

2018-06-28 02:29 UTC, jdpapiero commented on src/test/resources/features/Personal/Personal.feature
> +    Then El resultado de 'Buscar Personal' deberia ser <resultado>
the first letter in step description should be in lowercase

2018-06-28 02:53 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    @FindBy(xpath = "//button[@id='personal']")
If you use id for identify web element, you don't need use 'xpath', please use 'id'

2018-06-28 02:54 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
>      @FindBy(xpath = "//button[@id='users']")
If you use id for identify web element, you don't need use 'xpath', please use 'id'

2018-06-28 02:58 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personal/FindPersonal.java
> +    @FindBy(css = ".mat-paginator-range-label")
Are you sure this filter it's unique in your page?

2018-06-28 03:04 UTC, marbusjim commented on src/test/resources/features/Personal/Personal.feature
> +    Given 'Menu principal' estee cargado
I think the word 'estee' it's wrong

2018-06-28 15:03 UTC, jdpapiero requested changes
review observations

2018-06-28 15:03 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    private WebElement subMenuUsuario;
please change text to english. Ej.: subMenuUser

2018-06-28 15:03 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    private WebElement subMenuPersonal;
please change text to english. Ej.: subMenuPerson

2018-06-28 15:03 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
>      public ListUser selectSubMenuUsuario() {
please change text to english. Ej.: selectSubMenuUser

2018-06-28 15:03 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    public FindPersonal selectSubMenuPersonal() {
please change text to english. Ej.: selectSubMenuPerson

2018-06-28 15:03 UTC, jdpapiero commented on src/test/resources/features/Personal/Personal.feature
> +    When ingresar <correo> para 'Buscar Personal' en la tabla
rewrite better this step. Ej.: ingresar <correo> en el campo <Correo> de la pagina Personal para 'Buscar Personal' en la lista

2018-06-29 02:14 UTC, jdpapiero approved these changes
approve

2018-06-29 02:29 UTC, marbusjim approved these changes
approve

2018-06-29 02:32 UTC, ivanMise approved these changes

2018-06-29 02:33 UTC, merged

2018-06-29 02:36 UTC, ctola91 reviewed
Approved