RF01-TC-038
marcelogaray/auto-GA-v04 pull request #37
Opened 2018-06-24 15:44 UTC by danielrpg

RF01-TC-038

UI > Registro de Usuario > Verificar creación de un nuevo Usuario.

2018-06-24 15:53 UTC, danielrpg commented
![image](https://user-images.githubusercontent.com/1975854/41820771-cc8ed8ac-77a4-11e8-8f5f-2c211fb0bead.png)

2018-06-24 15:53 UTC, danielrpg commented
![image](https://user-images.githubusercontent.com/1975854/41820797-3b2818b4-77a5-11e8-96ae-791370db78a0.png)

2018-06-28 03:31 UTC, jdpapiero requested changes
review observations

2018-06-28 03:31 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/FormUser.java
> +    private WebElement usernameInputField;
change name of WebElement. Ej.: inputFieldUsername

2018-06-28 03:31 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/FormUser.java
> +    private WebElement passwordInputField;
change name of WebElement. Ej.: inputFieldPassword

2018-06-28 03:31 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/FormUser.java
> +    private WebElement userActiveInput;
change name of WebElement. Ej.: inputUserActive

2018-06-28 03:31 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    public void clickAddNewUser() {
change name Ej.: clickButtonAddNewUser

2018-06-28 03:31 UTC, jdpapiero commented on src/test/resources/features/users/createUser.feature
> +    Then Validar que la 'Lista de Usuarios' este visible
add a previous step of click button save

2018-06-28 03:37 UTC, ctola91 approved these changes

2018-06-28 03:57 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/FormUser.java
> +    private WebElement btnSaveUser;
change name of WebElement Ej.: buttonSaveUser

2018-06-28 04:04 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/FormUser.java
> +    public void createNewUserFromTable(DataTable userTable) {
You could use this example (http://toolsqa.com/cucumber/data-driven-testing-in-cucumber/) for send parameter and avoid use DataTable

2018-06-28 04:05 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/User.java
> +public class User {
I don't know if it's necessary to add a new class

2018-06-28 04:07 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listUser.isUserListVisible());
you need to add the error message

2018-06-28 04:11 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/User.java
> +public class User {
Yes because is necessary for persist user information from DataTable

2018-06-28 20:35 UTC, jdpapiero requested changes
please review observations

2018-06-28 20:35 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/FormUser.java
> +    private void clickUserActiveCheck(boolean userActive) {
please change name Ej.: clickCheckUserActive(

2018-06-28 20:35 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/FormUser.java
> +    public void clickButtonSaveUserButton() {
please rename for use just one Button Ej.: clickButtonSaveUser(

2018-06-28 20:35 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    private WebElement buttonAgregarUsuario;
rename WebElement for use everything in english. Ej.: buttonAddUser

2018-06-29 00:47 UTC, ctola91 reviewed
Approved

2018-06-29 00:51 UTC, ctola91 approved these changes

2018-06-29 01:08 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        listUser.clickButtonAddNewUser();
I think in this step you would return a new FormUser, because when you make a click this action redirected to formUser

2018-06-29 01:12 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        formUser = listUser.isFormUserVisible();
This step is only a visibility validation of a webElement, I think you don't get a formUser with this action.

2018-06-29 01:19 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        formUser.clickButtonSaveUser();
This action would return User List, because it will redirect a new page when save user

2018-06-29 01:58 UTC, marbusjim approved these changes

2018-06-29 02:01 UTC, merged