RF01TC045_TC_DanielFernandez-03
marcelogaray/auto-GA-v04 pull request #38
Opened 2018-06-25 12:11 UTC by danielrpg

UI > Registro de Usuario > Verificar creación de un nuevo Usuario.

2018-06-25 12:36 UTC, danielrpg commented
![image](https://user-images.githubusercontent.com/1975854/41850514-d5b6ad48-7852-11e8-901f-fa68282bfb73.png)

2018-06-25 12:38 UTC, danielrpg commented
![image](https://user-images.githubusercontent.com/1975854/41850595-1e3fb3b6-7853-11e8-80c7-9cab458389bb.png)

2018-06-29 02:40 UTC, marbusjim commented
Please review your TC and titles

2018-06-29 03:25 UTC, ctola91 requested changes

2018-06-29 03:25 UTC, ctola91 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    private WebElement smAssignSubMenu;
use subMenuSmAssign

2018-06-29 03:30 UTC, marbusjim reviewed
please solve the comments

2018-06-29 03:30 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    private WebElement smAssignSubMenu;
change to subMenuSmAssign

2018-06-29 04:14 UTC, marbusjim approved these changes
Approve

2018-06-30 00:19 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    @FindBy(xpath = "//button[@id='smAssign']")
use id please

2018-06-30 00:33 UTC, ivanMise approved these changes

2018-06-30 00:55 UTC, ctola91 approved these changes

2018-06-30 00:58 UTC, merged