Rf06 tc027 tc boris medrano 01
marcelogaray/auto-GA-v04 pull request #40
Opened 2018-06-25 17:51 UTC by borisytu2014

![lista contratos tc](https://user-images.githubusercontent.com/38248198/41866646-cbf74a5c-787e-11e8-8ab6-9ae0c55904ea.jpg)
![lista contratos](https://user-images.githubusercontent.com/38248198/41866649-cf375252-787e-11e8-8a4e-e186eeb06d05.jpg)

2018-06-28 04:01 UTC, ctola91 requested changes

2018-06-28 04:01 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    private WebElement paginaContrato;
Dont use Spanish in code

2018-06-28 04:01 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +        return CommonEvents.isVisible(paginaContrato);
Change Spanish to English

2018-06-28 04:01 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonalContract.java
> +    private WebElement subMenuContrato;
Change Spanish

2018-06-29 03:40 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/Menu.java
> +    public SubMenuPersonalContract selectPersonalSubMenuContract() {
change to selectSubMenuPersonalContract

2018-06-29 03:40 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        boolean result = listContract.validateContractList();
You don´t need add a variable, you should use directly in assertion

2018-06-29 03:47 UTC, marbusjim approved these changes
Approve

2018-06-29 04:16 UTC, danielrpg approved these changes
Review Changes

2018-06-29 04:23 UTC, merged