RF01TC041_TC_DanielFernandez-04
marcelogaray/auto-GA-v04 pull request #41
Opened 2018-06-26 02:21 UTC by danielrpg

UI >Registro de Usuario> Verificar la busqueda de usuarios
Se debe de ingresar a la 'Lista de usuarios' y ingresar en el campo de busqueda un numbre de usuario

2018-06-26 02:22 UTC, danielrpg commented
![image](https://user-images.githubusercontent.com/1975854/41885482-32ba5abc-78c6-11e8-8e58-e07caadc01b9.png)

2018-06-26 02:24 UTC, danielrpg commented
![image](https://user-images.githubusercontent.com/1975854/41885549-7747476c-78c6-11e8-91f4-5b9af73c9ef4.png)

2018-06-30 02:21 UTC, marbusjim commented on src/test/resources/features/users/searchUser.feature
> +    And completar campo 'Buscar Usuario' con los siguientes datos
please change to "insertar los siguientes datos en el cuadro de texto 'Buscar Usuario' en la pagina 'Lista de Usuarios'

2018-06-30 02:23 UTC, jdpapiero requested changes
review observations

2018-06-30 02:23 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +
remove this empty line

2018-06-30 03:14 UTC, ivanMise approved these changes

2018-06-30 03:25 UTC, jdpapiero requested changes
plase review observations

2018-06-30 03:25 UTC, jdpapiero commented on src/test/resources/features/assignequipament/assignEquipament.feature
> +Feature: Verificar formulario de asignacion Equipamiento a Personal
please first word in lowercase

2018-06-30 03:25 UTC, jdpapiero commented on src/test/resources/features/users/searchUser.feature
> +  Scenario: Verificar lista de Usuarios este correctamente cargado
this title of scenario is not the same to Test Case

2018-06-30 03:25 UTC, jdpapiero commented on src/test/resources/features/users/searchUser.feature
> +    Then verificar que el resultado coincida con el dato buscado
what is the previous step for find user? just set text in input? maybe is necesary to add a step ;)

2018-06-30 03:25 UTC, jdpapiero commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        listUser.fillFieldSearchWithData(searchUserTable);
what is the next step after fill data in search field? press enter key or click search?, please add a step to clarify

2018-06-30 03:34 UTC, danielrpg commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        listUser.fillFieldSearchWithData(searchUserTable);
On list users to filter by name is not necessary to click on any button, so is only see data on table list user filteres

2018-06-30 03:45 UTC, danielrpg commented on src/test/resources/features/users/searchUser.feature
> +    Then verificar que el resultado coincida con el dato buscado
When you filter user by name you dont need other step for validate information only table of user list

2018-06-30 04:20 UTC, marbusjim commented on src/test/resources/features/users/searchUser.feature
> +    Then verificar que el resultado coincida con el dato buscado
If I understand, when you write the word in TextField the table filtering the same time, that is true?

2018-06-30 04:24 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        listUser.fillFieldSearchWithData(searchUserTable);
If I understand it, when you type a word in the TextField, the table is filtered at the same time, is that true?

2018-07-01 00:39 UTC, danielrpg commented on src/test/resources/features/users/searchUser.feature
> +    Then verificar que el resultado coincida con el dato buscado
Yes is correct for this reason is not necessary  other estep for click other button

2018-07-01 00:40 UTC, danielrpg commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        listUser.fillFieldSearchWithData(searchUserTable);
It is related to search field and yes is correct for this reason is not necessary other estep for click other search button

2018-07-01 00:53 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        listUser.fillFieldSearchWithData(searchUserTable);
ok

2018-07-01 00:54 UTC, marbusjim commented on src/test/resources/features/users/searchUser.feature
> +Feature: check the users search
please use spanish

2018-07-01 00:55 UTC, marbusjim commented on src/test/resources/features/users/searchUser.feature
> +    Then verificar que el resultado coincida con el dato buscado
ok

2018-07-01 01:17 UTC, marbusjim approved these changes

2018-07-01 01:43 UTC, jdpapiero approved these changes
Approved

2018-07-01 01:44 UTC, merged