RF01TC042_TC_DanielFernandez-05
marcelogaray/auto-GA-v04 pull request #42
Opened 2018-06-26 04:50 UTC by danielrpg

UI >Registro de Usuario> Verificar la paginacion de la lista de usuario

Se debe de ingresar a la 'Lista de usuarios' y realizar la paginacion para validar que vuelva a listar

2018-06-26 04:52 UTC, danielrpg commented
![image](https://user-images.githubusercontent.com/1975854/41889949-3c7fb1f4-78db-11e8-85f3-f0ed82373f65.png)

2018-06-26 04:53 UTC, danielrpg commented
![image](https://user-images.githubusercontent.com/1975854/41889978-57d3ed3a-78db-11e8-8df9-b7faf63ced93.png)

2018-07-01 03:08 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    private WebElement btnNextPagination;
buttonNextPagination

2018-07-01 03:08 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    private WebElement btnPreviusPagination;
buttonPreviusPagination

2018-07-01 03:08 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    public void clickOnNextButton() {
clickButtonNext

2018-07-01 03:08 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    public void clickOnPreviusButton() {
clickButtonPrevius

2018-07-01 03:08 UTC, marbusjim commented on src/test/resources/features/users/pagNextPreviusUser.feature
> +    When seleccionar en boton next de la lista
seleccionar en boton 'next' del paginador de la 'lista de usuarios'

2018-07-01 03:08 UTC, marbusjim commented on src/test/resources/features/users/pagNextPreviusUser.feature
> +    And seleccionar en boton de previus de la lista
seleccionar en boton de 'previus' del paginador de la 'lista de usuarios'

2018-07-01 03:08 UTC, marbusjim commented on src/test/resources/features/users/pagNextPreviusUser.feature
> +    Then validar que la 'Lista de Usuarios' este visible
validar que la 'Lista de Usuarios' este visible en la pagina 'usuarios'

2018-07-01 03:28 UTC, marbusjim approved these changes
Approve

2018-07-01 04:06 UTC, jdpapiero requested changes
please review observations

2018-07-01 04:06 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    @FindBy(xpath = "//mat-cell[@class='mat-cell cdk-column-UserName mat-column-UserName ng-star-inserted']")
is necesary get better xpath, if you use class, choose use className

2018-07-01 04:06 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    @FindBy(xpath = "//button[@class='mat-paginator-navigation-next mat-icon-button']")
is necesary get better xpath, if you use class, choose use className or replace with id

2018-07-01 04:06 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    @FindBy(xpath = "//button[@class='mat-paginator-navigation-previous mat-icon-button']")
is necesary get better xpath, if you use class, choose use className or replace with id

2018-07-01 04:06 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Usuario/ListUser.java
> +    public void clickButtonPrevius() {
Previous

2018-07-01 18:20 UTC, merged

2018-07-01 18:29 UTC, jdpapiero reviewed
Review observations please

2018-07-01 18:29 UTC, jdpapiero commented on src/test/resources/features/users/pagNextPreviusUser.feature
> +    Then validar que la 'Lista de Usuarios' este visible en la pagina 'usuarios'
Change validar by verificar... the title of escenario say verificar but in the conclusión then say validar

2018-07-01 18:29 UTC, jdpapiero commented on src/test/resources/features/users/listUsers.feature
> +    Then validar que la 'Lista de Usuarios' este visible en la pagina 'usuarios'
Change validar by verificar... the title of escenario say verificar but in the conclusión then say validar