Rf07 tc001 tc ivan misericordia 02
marcelogaray/auto-GA-v04 pull request #43
Opened 2018-06-26 16:02 UTC by ivanMise

RF07-TC-001 UI >Registro de Equipamiento > Verificar cabecera de lista de Equipamientos (Nombre, Acciones).

![image](https://user-images.githubusercontent.com/32719964/41924535-51c5cc58-7938-11e8-9118-9dbca0854505.png)

![image](https://user-images.githubusercontent.com/32719964/41924702-ae19101e-7938-11e8-9a84-5c0347e1dd47.png)

2018-06-28 04:04 UTC, ctola91 requested changes

2018-06-28 04:04 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/ListEquipment.java
> +    private WebElement listNameRow;
Change name of element

2018-06-28 04:04 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/ListEquipment.java
> +    private WebElement listActionsRow;
Change name of element

2018-06-28 04:04 UTC, cmtp commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +    //BEGIN Equipment
Delete unnecesary comments

2018-06-28 04:04 UTC, cmtp commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +    @And("^seleccionar submenu 'Equipamiento' en menu 'Equipamiento'$")
Uppercase

2018-06-29 00:45 UTC, ctola91 requested changes

2018-06-29 00:45 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/ListEquipment.java
>      @FindBy(xpath = "/html/body/ssi-root/ssi-equipment/div/div[3]/div/div/mat-table/mat-header-row/mat-header-cell[2]")
Please dont use a large xpath

2018-06-29 00:45 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/ListEquipment.java
>      @FindBy(xpath = "/html/body/ssi-root/ssi-equipment/div/div[3]/div/div/mat-table/mat-header-row/mat-header-cell[1]")
Please dont use a large xpath

2018-06-29 00:45 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/ListEquipment.java
>      @FindBy(xpath = "/html/body/ssi-root/ssi-equipment/div/div[3]/div/div/mat-table/mat-header-row/mat-header-cell[2]")
Use contains maybe to fix this

2018-06-29 00:56 UTC, marbusjim reviewed
please review comments

2018-06-29 00:56 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/ListEquipment.java
> +    @FindBy(xpath = "/html/body/ssi-root/ssi-equipment/div/div[3]/div/div/mat-table/mat-header-row/mat-header-cell[1]")
Use a short xpath

2018-06-29 00:56 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/ListEquipment.java
> +    @FindBy(xpath = "/html/body/ssi-root/ssi-equipment/div/div[3]/div/div/mat-table/mat-header-row/mat-header-cell[2]")
Use a short xpath

2018-06-29 00:56 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listEquipment.checkHeaderListEquipment(), String.format(ErrorMessage.ERROR_MESSAGE_ELEMENT_VISIBLE, "Equiment title"));
you need verify headers in your list according your step, currently you only validate the list in page

2018-06-29 02:46 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +    @Then("^verificar cabecera 'Nombre' y 'Acciones' de la pagina 'Lista de Equipamientos' esten cargados$")
if you use this verification, you need add two validations (validationNameHeader and validationActionHeader)

2018-06-29 03:08 UTC, ctola91 approved these changes

2018-06-29 03:09 UTC, marbusjim approved these changes
Approve

2018-06-29 03:15 UTC, merged