UI >Registro de Equipamiento > Validar mensajes de error al intentar …
marcelogaray/auto-GA-v04 pull request #46
Opened 2018-06-26 17:23 UTC by ivanMise

RF07-TC-014 UI >Registro de Equipamiento > Validar mensajes de error al intentar crear un Equipamiento sin datos obligatorios.

![image](https://user-images.githubusercontent.com/32719964/41928716-24ee07fc-7944-11e8-81ea-a0a75c921a7e.png)

![image](https://user-images.githubusercontent.com/32719964/41928724-29c2d820-7944-11e8-8ef0-b4c1c9624732.png)

2018-06-30 04:42 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +        CommonEvents.clickButton(inputEquipmentName);
inputEquipmentName is a button?

2018-06-30 04:42 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +        CommonEvents.clickButton(textAreaEquipmentDesc);
inputEquipmentName is a button?

2018-06-30 04:42 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    public void clickInputFieldName() {
I think you should use a focus event and unfocus event instead of click event

2018-06-30 04:42 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    public void clickTextDescription() {
I think you should use a focus and unfocus event instead of click event

2018-06-30 04:42 UTC, marbusjim commented on src/test/resources/features/equipments/checkRequiredFields.feature
> +    And activar campo requerido 'Descripcion' sin ingresar informacion en 'Formulario de creación de Equipamiento'
you should add a lost focus steps

2018-06-30 05:03 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    public void clickTextDescription() {
Unfortunately WebElement does not have any of those options ...
Only skin with click ();
And CommonEvents.clickButton(WE) does that .. WE.click ();

2018-06-30 05:03 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    public void clickInputFieldName() {
Unfortunately WebElement does not have any of those options ...
Only skin with click ();
And CommonEvents.clickButton(WE) does that .. WE.click ();

2018-06-30 21:24 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    public void clickInputFieldName() {
I hope this video help you https://www.youtube.com/watch?v=vhiib87NnY0, you would add this function in CommonEvents class

2018-07-01 04:42 UTC, jdpapiero requested changes
please review observations

2018-07-01 04:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    @FindBy(xpath = "//p[4]/button")
change the xpath Ej.: //button[contains(text(),'limpiar imagen')]

2018-07-01 04:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    public void clickInputFieldName() {
try to use -> setInputField(inputEquipmentName, "")

2018-07-01 04:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +        CommonEvents.clickButton(inputEquipmentName);
try to use -> setInputField(inputEquipmentName, "")

2018-07-01 04:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    public void clickTextDescription() {
try to use -> setInputField(inputEquipmentName, "")

2018-07-01 04:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +        CommonEvents.clickButton(textAreaEquipmentDesc);
try to use -> setInputField(inputEquipmentName, "")

2018-07-01 04:42 UTC, jdpapiero commented on src/test/resources/features/equipments/checkRequiredFields.feature
> +    And activar campo requerido 'Descripcion' sin ingresar informacion en 'Formulario de creación de Equipamiento'
Maybe trying to use -> setInputField(webElement, "")

2018-07-01 18:08 UTC, marbusjim reviewed
review comments

2018-07-01 18:08 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    private WebElement hintMessageInputName;
please change to hiddenMessageInputName

2018-07-01 18:08 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Equipment/FormEquipment.java
> +    private WebElement hintMessageInputDescription;
please change to hiddenMessageInputDesciption

2018-07-01 18:42 UTC, danielrpg approved these changes
Code review aproved

2018-07-01 18:43 UTC, marbusjim approved these changes
approve

2018-07-01 18:58 UTC, jdpapiero approved these changes
Approved

2018-07-01 19:39 UTC, merged