RF05-TC-ChristianTola-012
marcelogaray/auto-GA-v04 pull request #53
Opened 2018-06-26 18:50 UTC by cmtp

Feature
![image](https://user-images.githubusercontent.com/9135312/41932863-3af5a832-7950-11e8-99d7-c83e19cc8b50.png)

2018-06-26 18:51 UTC, cmtp commented
![image](https://user-images.githubusercontent.com/9135312/41932898-5b7ea766-7950-11e8-8d0f-a479107eefbc.png)

2018-07-01 02:58 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    private WebElement cancelButton;
buttonCancel

2018-07-01 02:58 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    private WebElement toastMessage;
what's the meaning 'toast'?

messageToast

2018-07-01 02:58 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +        fillRadioButtonSeverity(data.get(0).get("Severity"));
checkRadioButtonServerity

2018-07-01 02:58 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    public void fillRadioButtonSeverity(String selectedRadioSeverity) {
checkRadioButtonServerity

2018-07-01 02:58 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/utils/CommonEvents.java
> +            System.out.println("Element do not exits.");
Remove this, because don't work with selenium framework

2018-07-01 02:58 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
remove this

2018-07-01 02:58 UTC, marbusjim commented on src/test/resources/features/Incident/Incident.feature
> +
you need separate your scenarios

2018-07-01 02:58 UTC, marbusjim commented on src/test/resources/features/Incident/Incident.feature
> +    And verificar que la tabla de incidentes se muestre correctamente
"Verificar que la 'tabla de incidentes' sea visible en la pagina de 'incidentes'

2018-07-01 02:58 UTC, marbusjim commented on src/test/resources/features/Incident/Incident.feature
> +    And hacemos 'click' en el boton 'Agregar nuevo Incidente'
click en el boton 'Agregar nuevo Incidente' de la pagina 'incidentes'

2018-07-01 02:58 UTC, marbusjim commented on src/test/resources/features/Incident/Incident.feature
> +    When insertamos informacion valida en el formulario de 'Creacion de Incidentes
insertamos información valida en el formulario de 'Creacion de Incidentes'

2018-07-01 02:58 UTC, marbusjim commented on src/test/resources/features/Incident/Incident.feature
> +    And hacemos clic en el boton de 'Guardar'
click en el boton 'guardar' en el 'formulario creación de incidentes'

2018-07-01 02:58 UTC, marbusjim commented on src/test/resources/features/Incident/Incident.feature
> +    Then verificar que la tabla de incidentes se muestre correctamente
verificar que la 'tabla de incidentes' este visible en la pagina 'Incidentes'

2018-07-01 02:58 UTC, marbusjim commented on src/test/resources/features/Incident/Incident.feature
> +    Then verificar que la tabla de incidentes se muestre correctamente
you need validate headers of table , currently you only validate if table it´s visible

2018-07-01 02:58 UTC, marbusjim commented on src/test/resources/features/Incident/Incident.feature
> +    Then verificar que la tabla de incidentes se muestre correctamente
your assertion don´t validate your scenario

2018-07-01 04:30 UTC, jdpapiero requested changes
please review observations

2018-07-01 04:30 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +            @FindBy(id = "mat-option-3"),
remove this repeated line

2018-07-01 04:30 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +            @FindBy(id = "mat-option-10"),
add the same line for mat-option-9

2018-07-01 04:30 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    private WebElement descriptionTextArea;
rename WebElement Ej.: textAreaDescription

2018-07-01 22:29 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    @FindBy(xpath = "//*[@id=\"form\"]/mat-card-actions/button[2]")
use: .//mat-card-actions/button[1]

2018-07-01 22:29 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    @FindBy(xpath = "//*[@id=\"form\"]/mat-card-actions/button[1]")
use: .//mat-card-actions/button[1]

2018-07-01 22:37 UTC, ivanMise commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +    @Then("^verificar que el boton de guardado no se deshabilita$")
maybe it could be: verificar que el boton 'guardar' no se deshabilita

2018-07-01 23:53 UTC, ctola91 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    private WebElement toastMessage;
Please review: 
http://www.sgoliver.net/blog/notificaciones-en-android-i-toast/
https://www.youtube.com/watch?v=OyhB8O0Gzmc

2018-07-01 23:53 UTC, ctola91 commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
Done

2018-07-01 23:53 UTC, ctola91 commented on src/test/resources/features/Incident/Incident.feature
> +
Those Scenarios are for this feature

2018-07-01 23:53 UTC, ctola91 commented on src/test/resources/features/Incident/Incident.feature
> +    When insertamos informacion valida en el formulario de 'Creacion de Incidentes
Done

2018-07-01 23:53 UTC, ctola91 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    private WebElement cancelButton;
Done

2018-07-01 23:53 UTC, ctola91 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +        fillRadioButtonSeverity(data.get(0).get("Severity"));
Done

2018-07-01 23:53 UTC, ctola91 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    public void fillRadioButtonSeverity(String selectedRadioSeverity) {
Done

2018-07-01 23:53 UTC, ctola91 commented on src/test/resources/features/Incident/Incident.feature
> +    And verificar que la tabla de incidentes se muestre correctamente
Done

2018-07-01 23:53 UTC, ctola91 commented on src/test/resources/features/Incident/Incident.feature
> +    And hacemos 'click' en el boton 'Agregar nuevo Incidente'
Done

2018-07-01 23:53 UTC, ctola91 commented on src/test/resources/features/Incident/Incident.feature
> +    And hacemos clic en el boton de 'Guardar'
Done

2018-07-01 23:53 UTC, ctola91 commented on src/test/resources/features/Incident/Incident.feature
> +    Then verificar que la tabla de incidentes se muestre correctamente
Done

2018-07-01 23:53 UTC, ctola91 commented on src/test/resources/features/Incident/Incident.feature
> +    Then verificar que la tabla de incidentes se muestre correctamente
Done

2018-07-01 23:53 UTC, ctola91 commented on src/test/resources/features/Incident/Incident.feature
> +    Then verificar que la tabla de incidentes se muestre correctamente
Done

2018-07-01 23:53 UTC, ctola91 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +            @FindBy(id = "mat-option-3"),
Done

2018-07-01 23:53 UTC, ctola91 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    private WebElement descriptionTextArea;
Done

2018-07-01 23:53 UTC, ctola91 commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +            @FindBy(id = "mat-option-10"),
Done

2018-07-01 23:53 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    @FindBy(xpath = "//*[@id=\"form\"]/mat-card-actions/button[2]")
done

2018-07-01 23:53 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Incident/CreateIncidentPage.java
> +    @FindBy(xpath = "//*[@id=\"form\"]/mat-card-actions/button[1]")
done

2018-07-01 23:53 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/utils/CommonEvents.java
> +            System.out.println("Element do not exits.");
done

2018-07-02 00:06 UTC, marbusjim approved these changes
approved

2018-07-02 00:21 UTC, danielrpg approved these changes
Aproved

2018-07-02 00:24 UTC, ctola91 commented
![image](https://user-images.githubusercontent.com/9135312/42140362-6f146eee-7d6c-11e8-8737-b80588c6643d.png)

![image](https://user-images.githubusercontent.com/9135312/42140380-aa923988-7d6c-11e8-9fed-0cdf04884111.png)

2018-07-02 00:24 UTC, merged

2018-07-10 02:47 UTC, cmtp commented
TC-01
![image](https://user-images.githubusercontent.com/9135312/42486352-b96a4c80-83c9-11e8-809c-627a30ade734.png)
TC-02
![image](https://user-images.githubusercontent.com/9135312/42486375-cdf032a0-83c9-11e8-8838-d8c8b0b6c238.png)
TC-03
![image](https://user-images.githubusercontent.com/9135312/42486395-e023d47c-83c9-11e8-9f48-df9ecb889d57.png)
TC-06
![image](https://user-images.githubusercontent.com/9135312/42486404-eac232a2-83c9-11e8-98b7-3022f63ee630.png)
TC-012
![image](https://user-images.githubusercontent.com/9135312/42486414-f7a5ad32-83c9-11e8-869f-a92a3ab4b234.png)