Add Login Feature
marcelogaray/auto-GA-v04 pull request #6
Opened 2018-06-16 02:12 UTC by cmtp

Create generic login feature for automation test

2018-06-16 02:14 UTC, cmtp commented
![image](https://user-images.githubusercontent.com/9135312/41494894-6d7df120-70e9-11e8-9ff0-b2569099361d.png)

2018-06-20 00:17 UTC, marcelogaray requested changes
review observations

2018-06-20 00:17 UTC, marcelogaray commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Login/Login.java
> +    @FindBy(tagName = "button")
use unique locator

2018-06-20 01:42 UTC, marcelogaray requested changes
review observation

2018-06-20 01:42 UTC, marcelogaray commented on src/test/resources/features/Home/Home.feature
> +    Given 'Home' Page is loaded
https://github.com/marcelogaray/auto-GA-v03/pull/14
Example
Given Im authenticated on 'SMARTHOUSE' page with properly credentials

2018-06-20 22:11 UTC, marcelogaray commented
Ok, thank you by the moment I will close it, please send me pull request atomics.

2018-06-20 22:11 UTC, closed without merging