Rf06 tc008 tc boris medrano 08
marcelogaray/auto-GA-v04 pull request #62
Opened 2018-06-26 22:24 UTC by borisytu2014

![imagen](https://user-images.githubusercontent.com/38248198/41942624-12b2ad2a-796e-11e8-9180-d8c4082d5703.png)
![imagen](https://user-images.githubusercontent.com/38248198/41942634-1ecc94fe-796e-11e8-8cf0-589fd9ce02ca.png)

2018-06-30 22:45 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private WebElement fillContract;
please change to inputContract

2018-06-30 22:45 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +
remove this line

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +  Scenario: Agregar nuevo contrato
your scenario it's wrong for this feature, chage to "Validacion de funcionalidad del bonton 'atras' en la pagina de 'creacion de contrato'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +Feature: Back button contract
Please use Spanish

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +    And seleccionar boton Agregar Nuevo Contrato del Area de contratos
change to "seleccionar boton 'Agregar Nuevo Contrato' en la pagina, de la seccion 'Area de contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +    And seleccionar el boton 'Atras' del formulario creacion de contratos
change to "seleccionar el boton 'Atras' del formulario 'creacion de contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +    Then validar que la 'Lista de Contratos' este visible
change to "validar que la 'Lista de Contratos' este visible en la pagina 'Contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +
remove this line

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/CreateContract.feature
> +    And mostrar 'Lista de Contratos'
change to "visualizar el 'Lista de Contratos' de la pagina 'Contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +    And mostrar 'Lista de Contratos'
Change to "visualizar 'Lista de Contratos' de la pagina 'Contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/CreateContract.feature
> +    And seleccionar boton Agregar Nuevo Contrato del Area de contratos
chage to "seleccionar el boton 'Agregar Nuevo Contrato' de la pagina 'Area de contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/CreateContract.feature
> +Feature: Create Contract
please use Spanish

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/CreateContract.feature
> +    And llenar 'formulario de Contrato Nuevo'
chage to "registra informacion valida en el formuladio de 'Creacion nuevo contrato' de la pagina 'Creacion contrato'

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/CreateContract.feature
> +    Then seleccionar Boton 'Enviar' para grabar los datos del formulario
this is a step, you need add a assertion, for Example, "Validar que el mensaje de guadado sastisfactorio sea visible"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/DeleteContract.feature
> +Feature: Delete Contract
use spanish

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/DeleteContract.feature
> +    And mostrar 'Lista de Contratos'
change to "visualizar la 'Lista de Contratos' de la pagina 'Contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/DeleteContract.feature
> +    And seleccionar boton Eliminar del primer item lista contratos
chage to "click en el botton 'Eliminar' del primer item de las lista de contratos en el pagina 'contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/FindContract.feature
> +Feature: Find Contract
use spanish

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/FindContract.feature
> +    And mostrar 'Lista de Contratos'
change to "visualizar la 'Lista de Contratos' de la pagina 'Contratos'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/FindContract.feature
> +  Scenario: Verificar lista de Contratos este correctamente cargado
Validate the detail of scenario

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/FindContract.feature
> +    And llenar la opcion filtro de contrato
change to "insertar la siguiente informacion para realizar el filtro en la 'lista de contrato'"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/FindContract.feature
> +    Then validar que la 'Lista de Contratos' este visible mostrando el filtro ingresado
change to "Validar que la 'lista de contratos' se haya filtrado correctamente"

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/NavListContract.feature
> +Feature: Contract navigation list
use spanish

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/NavListContract.feature
> +  Scenario: Verificar lista de Contratos este correctamente cargado
please review the detail of scenario

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/TitleCreateContract.feature
> +  Scenario: Agregar nuevo contrato
validate the detail of scenario

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/UpdateContract.feature
> +Feature: Update Contract
use spanish

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/TitleCreateContract.feature
> +Feature: Title create Contract
use spanish

2018-06-30 22:45 UTC, marbusjim commented on src/test/resources/features/Contract/UpdateContract.feature
> +  Scenario: Verificar lista de Contratos este correctamente cargado
validate the detail of scenario

2018-07-01 12:42 UTC, jdpapiero requested changes
review observations

2018-07-01 12:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +        CommonEvents.setInputField(inputCodeContract, data.get(0).get("contractCodes"));
is necesary separate every action in a method and just call in here Ej.:
setDataInputCode(string);
setDataInputDescriotion(string);
setDataInputSalary();
...
..

private void setInputDataCode(String data)
{ CommonEvents.setInputField(inputDataCode, data);}
...
...

2018-07-01 12:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +        CommonEvents.setInputField(inputCodeEditContract, data.get(0).get("contractCodesEdit"));
change like observation of newContractRegistration()

2018-07-01 12:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    public boolean btnSendForm(){
rename Ej.: clickButtonSendForm()

2018-07-01 12:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    public boolean btnSendFormEdit(){
rename Ej.: clickButtonSendFormEdit()

2018-07-01 12:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    @FindBy(xpath = "//button[@class='mat-paginator-navigation-next mat-icon-button']")
if your selector is by class, you should use className, not xpath

2018-07-01 12:42 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    @FindBy(xpath = "//button[@class='mat-paginator-navigation-previous mat-icon-button']")
if your selector is by class, you should use className, not xpath

2018-07-01 18:40 UTC, marbusjim reviewed
review comments

2018-07-01 18:40 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private WebElement inputFillContract;
change to inputFindContract

2018-07-01 18:40 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    public FormContract selectBtnEditContract() {
add a line

2018-07-01 18:40 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(formContract.clickButtonSendFormEdit(), String.format(ErrorMessage.ERROR_MESSAGE_ELEMENT_VISIBLE, "Send Form Edit"));
Are you sure this assertion it's corrected?, the assertion should validate after click event

2018-07-01 18:40 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listContract.selectBackListcontract(), String.format(ErrorMessage.ERROR_MESSAGE_ELEMENT_VISIBLE, "Button Back Contract"));
Are you sure this assertion it is corrected?, the assertion should validate after click event

2018-07-01 18:40 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listContract.selectNextListcontract(), String.format(ErrorMessage.ERROR_MESSAGE_ELEMENT_VISIBLE, "Button Next Contract"));
Are you sure this assertion it is corrected?, the assertion should validate after click event

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +    And mostrar 'Lista de Contratos'
change to "visualizacion de la 'Lista de Contratos' en la pagina 'Contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +    And seleccionar el boton 'Atras' del formulario creacion de contratos
change to "seleccionar el boton 'Atras' del formulario 'creacion de contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/BtnBackContract.feature
> +    Then validar que la 'Lista de Contratos' este visible
change to "validar que la 'Lista de Contratos' este visible en la pagina 'Contrato'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/DeleteContract.feature
> +    And mostrar 'Lista de Contratos'
change to "visualizacion del 'Lista de Contratos' de la pagina 'Contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/FindContract.feature
> +    And mostrar 'Lista de Contratos'
change to "visualizacion del 'Lista de Contratos' de la pagina 'Contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/NavListContract.feature
> +    When seleccionar en boton siguiente de la lista
chage to "seleccionar en boton 'siguiente' de la lista de 'contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/NavListContract.feature
> +    And seleccionar en boton de anterior de la lista
chage to "seleccionar en boton 'anterior' de la lista de 'contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/TitleCreateContract.feature
> +    And mostrar 'Lista de Contratos'
change to "visualizacion del 'Lista de Contratos' de la pagina 'Contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/TitleCreateContract.feature
> +    And seleccionar boton Agregar Nuevo Contrato del Area de contratos
change to "click en el boton 'Agregar Nuevo Contrato' del 'Area de contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/UpdateContract.feature
> +    And mostrar 'Lista de Contratos'
change to "visualizacion del 'Lista de Contratos' de la pagina 'Contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/UpdateContract.feature
> +    And seleccionar boton Editar del primer item lista contratos
change to "click en el boton 'Editar' del primer item de la 'lista de contratos'"

2018-07-01 18:40 UTC, marbusjim commented on src/test/resources/features/Contract/UpdateContract.feature
> +    Then seleccionar boton 'Enviar' para grabar los datos editados del formulario
chage to "seleccionar boton 'Enviar' para guardar los datos editados del formulario"

you need add assertion "Validar que el mensaje de guardo satisfactoriamente se visualice"

2018-07-01 20:00 UTC, jdpapiero requested changes
Review observatios

2018-07-01 20:00 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    public FormContract() {}
Is necesary add commonevents.isvisible of some webelement.. inner constructor... for wait page object.. please add this

2018-07-01 20:00 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    public void clickButtonSendForm(){
This method do not return anything?

2018-07-01 21:18 UTC, marbusjim commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    public void clickButtonSendFormEdit(){
This method do not return anything?

2018-07-01 22:54 UTC, marbusjim approved these changes
approved

2018-07-01 23:05 UTC, danielrpg approved these changes
Aproved

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private WebElement btnSendContract;
Please use button instead btn on variable name, example buttonSendContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private WebElement btnSendEdit;
Please use button instead btn on variable name, example buttonSendEdit

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +        CommonEvents.clickButton(btnSendContract);
change to buttonSendContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +        return CommonEvents.isVisible(btnSendEdit);
Change a buttonSendEdit

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    private WebElement btnEditContract;
Change this variable name instead buttonEditContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    private WebElement btnDeleteContract;
Change this varable name to buttonDeleteContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    private WebElement btnNextListcontract;
Change this to buttonNextListContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    private WebElement btnBackListcontract;
Change this variable to buttonBackListContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +    @FindBy(id = "btnAtras")
Change this variable name to buttonBack

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +        CommonEvents.clickButton(btnAddContract);
Change btnAddContract to buttonAddContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +        CommonEvents.clickButton(btnEditContract);
Change btnEditContract to buttonEditContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +        CommonEvents.clickButton(btnDeleteContract);
Change btnDeleteContract to buttonDeleteContract

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +        CommonEvents.clickButton(btnNextListcontract);
change btn to button

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +        return CommonEvents.isVisible(btnNextListcontract);
Change btn to button

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +        return CommonEvents.isVisible(btnBackListcontract);
Change btn to button

2018-07-01 23:05 UTC, danielrpg commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/ListContract.java
> +        CommonEvents.clickButton(btnBackList);
change btn to button

2018-07-02 00:05 UTC, ctola91 requested changes

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    public FormContract(){ CommonEvents.isVisible(formContract);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private void setInputDataCode(String data){ CommonEvents.setInputField(inputCodeContract, data);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private void setInputDataDescription(String data){ CommonEvents.setInputField(inputDescriptionContract, data);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private void setInputDataSalary(String data){ CommonEvents.setInputField(inputSalaryContract, data);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private void setInputDataDate(String data){ CommonEvents.setInputField(inputDateContract, data);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private void setInputDataCodeEdit(String data){ CommonEvents.setInputField(inputCodeEditContract, data);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private void setInputDataDescriptionEdit(String data){ CommonEvents.setInputField(inputDescriptionEditContract, data);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private void setInputDataSalaryEdit(String data){ CommonEvents.setInputField(inputSalaryEditContract, data);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    private void setInputDataDateEdit(String data){ CommonEvents.setInputField(inputDateEditContract, data);}
Please format code

2018-07-02 00:05 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Contract/FormContract.java
> +    public void findContractList(List<Map<String, String>> data) { CommonEvents.setInputField(inputFindContract, data.get(0).get("contractCode"));}
Please format code

2018-07-02 00:13 UTC, ctola91 approved these changes

2018-07-02 00:13 UTC, merged