Verificar cabecera de lista de Personal
marcelogaray/auto-GA-v04 pull request #73
Opened 2018-06-30 21:57 UTC by franzelunico

2018-07-01 20:32 UTC, jdpapiero requested changes
Review observations

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    @FindBy(xpath = "//button[@id='personal']")
Chage for use @FindBy(id=...

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
>      @FindBy(xpath = "//button[@id='users']")
Chage for use @FindBy(id=...

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    private WebElement personalSubMenu;
Chante. subMenuPersonal

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    }
After click event... return the pageobject that you need for continue your steps

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ListPersonnel.java
> +    public boolean validateListPersonnel() {
Rename validateListPersonnelIsVisible(

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ListPersonnel.java
> +    public boolean validateName() {
Rename validateTableListNameIsVisible

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ListPersonnel.java
> +    public boolean validateLastName() {
Rename validateTableListLastNameIsVisible

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ListPersonnel.java
> +    public boolean validateEmail() {
Rename validateTableEmailIsVisible

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ListPersonnel.java
> +    public boolean validateAddress() {
Rename validateTableListAdressIsVisible

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ListPersonnel.java
> +    public boolean validatePhone() {
Rename validateTableLisPhoneIsVisible

2018-07-01 20:32 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ListPersonnel.java
> +    public boolean validateAction() {
Rename validateTableListActionIsVisible

2018-07-01 20:32 UTC, jdpapiero commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Thread.sleep(4000);
Remove this line... is not able use sleep function... add return page object inner method seleccionarSubMenu to solve

2018-07-01 20:32 UTC, jdpapiero commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        listPersonnel = new ListPersonnel();
Obtain the page object in previous step in return action

2018-07-02 00:11 UTC, ctola91 requested changes

2018-07-02 00:11 UTC, cmtp commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +    public void seleccionarSubMenuPersonal(){
Don't use spanish

2018-07-02 16:56 UTC, ctola91 approved these changes

2018-07-02 19:23 UTC, ivanMise approved these changes

2018-07-02 19:23 UTC, ivanMise commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        listPersonnel = new ListPersonnel();
you should get that instance (ListPersonel) 
when doing click in subMenuPersonnel 
maybe you could change  SubMenuPersonnel.java Ej: public ListPerosnel selectSubMenuPersonnel() {
        boolean res = CommonEvents.isVisible(subMenuPersonnel);
        if (res) {
            CommonEvents.clickButton(subMenuPersonnel);
        }
        return new ListPersonnel();
    }

2018-07-03 05:22 UTC, marbusjim reviewed
with comments

2018-07-03 05:22 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listPersonnel.validateListPersonnelIsVisible());
add error message

2018-07-03 05:22 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listPersonnel.validateNameIsVisible());
add error message

2018-07-03 05:22 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listPersonnel.validateLastNameIsVisible());
add error message

2018-07-03 05:22 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listPersonnel.validateEmailIsVisible());
add error message

2018-07-03 05:22 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listPersonnel.validateAddressIsVisible());
add error message

2018-07-03 05:22 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listPersonnel.validatePhoneIsVisible());
add error message

2018-07-03 05:22 UTC, marbusjim commented on src/test/java/org/umssdiplo/automationv01/stepdefinitionproject/StepsDefinitionSSID.java
> +        Assert.assertTrue(listPersonnel.validateActionIsVisible());
add error message

2018-07-10 03:23 UTC, jdpapiero commented
please review observations, this PR would by closed until fix them

2018-07-10 03:23 UTC, closed without merging