Verificar la creación de un nuevo Personal
marcelogaray/auto-GA-v04 pull request #77
Opened 2018-07-02 06:24 UTC by franzelunico

![image](https://user-images.githubusercontent.com/4955089/42148067-b7178e60-7d9e-11e8-8a00-b63562867b3f.png)
![image](https://user-images.githubusercontent.com/4955089/42148103-e74a2462-7d9e-11e8-990e-87beb7a83f55.png)

2018-07-02 13:55 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/AddPersonnel.java
> +    public void setName(String name) {
maybe you could change to: setInputFieldName(String name)

2018-07-02 13:56 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/AddPersonnel.java
> +    public void setLastName(String lastName) {
maybe you could change to: setInputFieldLastName(String lastName)

2018-07-02 13:56 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/AddPersonnel.java
> +    public void setEmail(String email) {
maybe you could change to: setInputFieldEmail(String email)

2018-07-02 13:57 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/AddPersonnel.java
> +    public void setAddress(String address) {
maybe you could change to: setInputFieldAddress(String address)

2018-07-02 13:58 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/AddPersonnel.java
> +    public void setPhone(String phone) {
maybe you could change to: setInputFieldPhone(String phone)

2018-07-02 13:59 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/AddPersonnel.java
> +            CommonEvents.clickButton(optionAreaPersonnel);
maybe you could change to: setOptionArea()

2018-07-02 14:03 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/AddPersonnel.java
> +    public boolean send() {
complement the name of this methodo send () or maybe you could change to: clickOnButtonSendPersonnel ()

2018-07-02 14:05 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ButtonAddPersonnel.java
> +    public boolean validateButtonAddPersonnel(){
maybe you could change to: validateButtonAddPersonnelIsVisible()

2018-07-02 14:07 UTC, ivanMise commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Personnel/ButtonAddPersonnel.java
> +    public AddPersonnel clickAgregarPersonal(){
use english please.
maybe you could change to: clickOnButtonAddPersonnel()

2018-07-02 18:19 UTC, ivanMise approved these changes

2018-07-10 03:18 UTC, jdpapiero requested changes
please review observations, this PR would by closed until fix them

2018-07-10 03:18 UTC, jdpapiero commented on src/main/java/org/umssdiplo/automationv01/core/managepage/Menu/SubMenuPersonal.java
> +import org.umssdiplo.automationv01.core.managepage.Personnel.ButtonAddPersonnel;
review the pageobject buttonaddpersonnel, maybe this button should be in AddPersonnel

2018-07-10 03:18 UTC, jdpapiero commented on src/test/resources/features/Personnel/addPersonnel.feature
> +    Given click en el boton 'Agregar nuevo personal'
already exist a Given in this feature

2018-07-10 03:18 UTC, jdpapiero commented on src/test/resources/features/Personnel/addPersonnel.feature
> +    When llenar el campo apellido <apellido>
Already exist 'When' consecutive in this feature, maybe the correct sintaxt should be And.
When
And
And
And
Then

2018-07-10 03:18 UTC, jdpapiero commented on src/test/resources/features/Personnel/addPersonnel.feature
> +    When llenar el campo email <email>
Already exist 'When' consecutive in this feature, maybe the correct sintaxt should be And.
When
And
And
And
Then

2018-07-10 03:18 UTC, jdpapiero commented on src/test/resources/features/Personnel/addPersonnel.feature
> +    When llenar el campo direccion <direccion>
Already exist 'When' consecutive in this feature, maybe the correct sintaxt should be And.
When
And
And
And
Then

2018-07-10 03:18 UTC, jdpapiero commented on src/test/resources/features/Personnel/addPersonnel.feature
> +    When llenar el campo telefono <telefono>
Already exist 'When' consecutive in this feature, maybe the correct sintaxt should be And.
When
And
And
And
Then

2018-07-10 03:18 UTC, jdpapiero commented on src/test/resources/features/Personnel/addPersonnel.feature
> +    When seleccionar el 'Area' de instalaciones hidricas
Already exist 'When' consecutive in this feature, maybe the correct sintaxt should be And.
When
And
And
And
Then

2018-07-10 03:19 UTC, jdpapiero commented
please review observations, this PR would by closed until fix them

2018-07-10 03:19 UTC, closed without merging